#!/bin/sh

mkdir -p /data/transcode
ln -s /usr/bin/ffmpeg /data/transcode/ffmpeg
ln -s /usr/bin/lame /data/transcode/lame

chown -R $UID:$GID /data ${PLAYLISTS_FOLDER} ${PODCASTS_FOLDER} /subsonic

if [ $# == 0 ]; then
    exec su-exec $UID:$GID /sbin/tini -- $@
else
    exec su-exec $UID:$GID /sbin/tini -- java -Xmx256m \
        -Dsubsonic.home=/data \
        -Dsubsonic.host=0.0.0.0 \
        -Dsubsonic.port=4040 \
        -Dsubsonic.httpsPort=${HTTPSPORT} \
        -Dsubsonic.contextPath=${WEBROOT} \
        -Dsubsonic.defaultMusicFolder=${MUSICS_FOLDER} \
        -Dsubsonic.defaultPodcastFolder=${PODCASTS_FOLDER} \
        -Dsubsonic.defaultPlaylistFolder=${PLAYLISTS_FOLDER} \
        -Djava.awt.headless=true \
        -jar subsonic-booter-jar-with-dependencies.jar
fi
